### ISSUE TITLE
Missing dependency x264

### ISSUE THREAD

**Issue by Enelar** [GloriousEggroll/arch-obs-studio-latest-ffmpeg-vaapi#4]
Are you sure that libva isnt enough?

**Comment by GloriousEggroll** [comment]
yes, I'm sure. I've been using the same build and compiling it over the
past year

**Comment by Enelar** [comment]
damn, what i should do to make in compilable? cause i cant find any 'x264' in aur or repos

**Comment by GloriousEggroll** [comment]
makepkg -cs should auto-install whatever dependencies are needed
