### ISSUE TITLE
Recording 1080p@60fps always overloads encoder

### ISSUE THREAD

**Issue by Readek** [GloriousEggroll/arch-obs-studio-latest-ffmpeg-vaapi#5]
So I've recently swapped nvidia for amd (in this case I got a RX480) and seems like its harder to get OBS working with an AMD hardware encoding. I found this patch and yay I can now use OBS without using 70% of my CPU. But theres a critical problem.

For some reason, if I record at [1080p@60fps](https://streamable.com/kd13n), encoder will ALWAYS overload. Even when theres no game running and obs only has a black screen. I tried [720p@60fps](https://streamable.com/i1f4u), 1080p@30fps and even [1080p@30fps with 20k bitrate](https://streamable.com/wpq8d) to see if it overloaded but they all worked properly. And just in case I also tried with [1080p@60fps x264 encoding](https://streamable.com/cfjx1) to see if it was just my OBS, and it ran just fine.

I am on Manjaro running mesa 18.0.3, but this also happened on Solus. Just in case, I'll leave my settings here:

![image](https://user-images.githubusercontent.com/35299560/39776698-e03571c6-5301-11e8-9688-464499b379b0.png)

**Comment by Readek** [comment]
Seems like those were the default options.
![image](https://user-images.githubusercontent.com/35299560/39873367-fad56b84-546a-11e8-9475-c88f699c782c.png)

**Comment by GloriousEggroll** [comment]
hmm, I wonder if this is either a vce 3.4 restriction (rx non-vega series), or a mesa bug. I just tested again on my vega 64 and recorded 1080p60 @ 30,000 bitrate with no problem on tomb raider benchmark using xcomposite window capture

**Comment by GloriousEggroll** [comment]
I found the issue, which is not related to my patches. The encoder shares resources with the gpu, it is not dedicated hardware. If the GPU is unable to maintain the set framerate by a certain amount (usually less than 10 frames), the encoder reports being overloaded. This can be resolved by lowering your games graphics settings so that you get whatever the framerate is set to. 

I did a test with the intro scene with rise of the tomb raider, and managed to alleviate this by turning the graphics preset to medium, disabling depth of field, tessellation, and purehair. I also used fxaa. Graphics intensive portions of the intro include when ana comes through the door and when they are talking while lara is sifting through things. I was also able to reproduce this issue/fix with wolfenstein II

**Comment by Readek** [comment]
Did we forget the fact that the encoder will overload even if no game is running? For example, when at 1080@60fps, if I use a media source video and nothing else (no game in the background), the media source will lag on the recording.

**Comment by GloriousEggroll** [comment]
Mine does not overload at all with no game running. My only other thought is that either mesa has an issue/bug or vce 3.4 struggles with 1080p60 encoding. Have you tried recording with simple screen recorder to test if it occurs there?

**Comment by ICHx** [comment]
how about if you try recording using purely ffmpeg and see

**Comment by Readek** [comment]
How do I make sure to test pure ffmpeg? Also, tried x264 recording a media source 1080@60fps, it did not overload.

**Comment by Readek** [comment]
Alright I went to arch wiki to learn how to do that, let me know if I did it right:

`ffmpeg -f x11grab -video_size 1920x1080 -framerate 60 -i $DISPLAY -f alsa -i default -r 60 -s 1920x1080 -c:v libx264 -preset:v veryfast -b:v 2000k -c:a libopus -b:a 128k test.mkv`

And [it seems to be working perfectly](https://streamable.com/zd6a3).

**Comment by GloriousEggroll** [comment]
libx264 is for x264, not h264. please use the format i posted in my
previous response

**Comment by Readek** [comment]
I removed "-x 1920" since it was preventing me from recording:

`[x11grab @ 0x55e37fb01820] Capture area 1920x1080 at position 1920.0 outside the screen size 3200x1080
:0.0: Invalid argument`

I ran it and... well, [seems like we found a problem](https://streamable.com/g0lj4).

**Comment by GloriousEggroll** [comment]
can you try with -quality 3
and also try 4 and 5

**Comment by Readek** [comment]
Did a test with 3, 4, 5, and 8. All of them were laggy.

**Comment by ICHx** [comment]
/dev/dri/renderD129 :thinking: 
Do you know which one, either D128 or D129, is your RX card

**Comment by ICHx** [comment]
btw, also please try disabling unnecessary graphics effects

**Comment by Readek** [comment]
I made sure mine was D128. Also, I did tests without desktop compositor, with the same results.

Anyways, this seems like its out of the patch's reach so you can already close the issue.

**Comment by GloriousEggroll** [comment]
just fyi more details on this:
https://github.com/obsproject/obs-studio/pull/1256#issuecomment-393018169

**Comment by Readek** [comment]
Yeah, already saw it. But the RX480 is not a weak card, it should be more than enough for 1080p recording. And this happens even when no game is running. So I doubt that's the reason...

**Comment by GloriousEggroll** [comment]
I'm not saying it's a weak card, I'm saying the hardware encoder is dependent on the strength of the card. In my comment i said the rx 550 was not even able to record anything at 60fps,however all resolutions at 30 fps worked fine. Seeing as your card was able to do 720p60 and 1080p30 just fine, and my vega was able to do 1080p60, it reinforces that it probably comes down the the strength of the card and/or the encoding hardware on the card.

**Comment by GloriousEggroll** [comment]
I found something interesting. My encoder overloads with window capture (xcomposite) but does not overload with screen capture. can you try using screen capture?

**Comment by Readek** [comment]
Encoder will overload anyways even when theres no source added.

**Comment by GloriousEggroll** [comment]
Can you try disabling the preview in obs?

**Comment by Readek** [comment]
Yes, encoder overloaded without preview.

**Comment by unixfox** [comment]
I've the same issue as @Readek, my GPU is an AMD RX480 running on ArchLinux.
